// AUTO-GENERATED by portfolio-sync — do not edit manually
// Last synced: 2026-06-12T18:58:00.241Z
// To update: trigger the "Sync Portfolio" workflow in GitHub Actions.

export type ProjectDomain = "Data Analysis" | "Agentic AI" | "ML" | "Full Stack";

export interface Project {
  id: number;
  title: string;
  description: string;
  tags: string[];
  domains: ProjectDomain[];
  githubUrl: string;
  image: string;
}

export interface SkillCategory {
  name: string;
  skills: string[];
}

export const projects: Project[] = [
  {
    "id": 1,
    "title": "HireLens",
    "description": "HireLens is an AI-powered system that matches resumes to job descriptions by leveraging semantic embeddings and NER-based skill extraction. It offers dual views for candidates to analyze individual resumes and for recruiters to rank and filter resumes in bulk, enhancing the recruitment process with precision and efficiency.",
    "tags": [
      "FastAPI",
      "React",
      "spaCy",
      "MiniLM",
      "AWS EC2"
    ],
    "domains": [
      "ML",
      "Full Stack"
    ],
    "image": "🔍",
    "githubUrl": "https://github.com/Akshats-git/HireLens"
  },
  {
    "id": 2,
    "title": "WhatsApp Chat Analyzer",
    "description": "WhatsApp Chat Analyzer is an interactive web application that provides detailed insights into your WhatsApp conversations. By analyzing exported chat data, it generates visualizations and statistics on message activity, word usage, and emoji frequency, offering a comprehensive view of communication patterns. It's a valuable tool for anyone interested in understanding their messaging habits or group dynamics.",
    "tags": [
      "Streamlit",
      "Pandas",
      "Matplotlib",
      "Seaborn",
      "Plotly"
    ],
    "domains": [
      "Data Analysis"
    ],
    "image": "📊",
    "githubUrl": "https://github.com/Akshats-git/Whatsapp-Chat-Analyzer"
  }
];

export const skillCategories: SkillCategory[] = [
  {
    "name": "Frontend",
    "skills": [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Redux",
      "JavaScript",
      "CSS",
      "HTML"
    ]
  },
  {
    "name": "Backend",
    "skills": [
      "Node.js",
      "Express",
      "Python",
      "FastAPI"
    ]
  },
  {
    "name": "Databases",
    "skills": [
      "PostgreSQL",
      "MongoDB",
      "Firebase",
      "Redis",
      "MySQL"
    ]
  },
  {
    "name": "Tools & Platforms",
    "skills": [
      "Git",
      "Docker",
      "AWS",
      "Vercel",
      "GitHub Actions",
      "VS Code",
      "Shell"
    ]
  },
  {
    "name": "UI/UX & Design",
    "skills": [
      "Figma",
      "Shadcn UI",
      "Material-UI"
    ]
  },
  {
    "name": "Agentic Frameworks",
    "skills": [
      "LangChain",
      "Hugging Face",
      "RAG Systems",
      "LangGraph"
    ]
  }
];
