// AUTO-GENERATED by portfolio-sync — do not edit manually
// To update: add "portfolio-ready" topic to a GitHub repo, then trigger
// the "Sync Portfolio" workflow in GitHub Actions.

export type ProjectDomain = "Data Analysis" | "Agentic AI" | "ML" | "Full Stack";

export interface Project {
  id: number;
  title: string;
  description: string;
  tags: string[];
  domains: ProjectDomain[];
  githubUrl: string;
  image: string;
}

export interface SkillCategory {
  name: string;
  skills: string[];
}

export const projects: Project[] = [
  {
    id: 1,
    title: "Whatdapp Chat Analyzer",
    description:
      "A WhatsApp chat analysis tool that extracts insights, sentiment trends, activity patterns, and word frequency statistics from exported chat logs.",
    tags: ["Python", "NLP", "Pandas", "Streamlit"],
    domains: ["Data Analysis"],
    githubUrl: "https://github.com",
    image: "💬",
  },
  {
    id: 2,
    title: "HireLens",
    description:
      "An AI-powered recruitment assistant that screens resumes, matches candidates to job descriptions, and generates structured interview questions using LLMs.",
    tags: ["LangChain", "FastAPI", "React", "PostgreSQL"],
    domains: ["Agentic AI", "Full Stack"],
    githubUrl: "https://github.com",
    image: "🔍",
  },
  {
    id: 3,
    title: "Youtube Chatbot",
    description:
      "A RAG-based chatbot that ingests YouTube video transcripts and lets users ask questions, get summaries, and explore content through natural conversation.",
    tags: ["LangChain", "RAG", "Next.js", "OpenAI API"],
    domains: ["Agentic AI", "Full Stack"],
    githubUrl: "https://github.com",
    image: "▶️",
  },
];

export const skillCategories: SkillCategory[] = [
  {
    name: "Frontend",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "Redux"],
  },
  {
    name: "Backend",
    skills: ["Node.js", "Express", "Python", "FastAPI"],
  },
  {
    name: "Databases",
    skills: ["PostgreSQL", "MongoDB", "Firebase", "Redis", "MySQL"],
  },
  {
    name: "Tools & Platforms",
    skills: ["Git", "Docker", "AWS", "Vercel", "GitHub Actions", "VS Code"],
  },
  {
    name: "UI/UX & Design",
    skills: ["Figma", "Shadcn UI", "Material-UI"],
  },
  {
    name: "Agentic Frameworks",
    skills: ["LangChain", "Hugging Face", "RAG Systems", "LangGraph"],
  },
];
