// AUTO-GENERATED by portfolio-sync — do not edit manually
// Last synced: 2026-06-12T18:35:52.246Z
// To update: trigger the "Sync Portfolio" workflow in GitHub Actions.

export type ProjectDomain = "Data Analysis" | "Agentic AI" | "ML" | "Full Stack";

export interface Project {
  id: number;
  title: string;
  description: string;
  tags: string[];
  domains: ProjectDomain[];
  githubUrl: string;
  image: string;
}

export interface SkillCategory {
  name: string;
  skills: string[];
}

export const projects: Project[] = [
  {
    "id": 1,
    "title": "WhatsApp Chat Analyzer",
    "description": "The WhatsApp Chat Analyzer is an interactive web application that provides in-depth analysis of exported WhatsApp chats. It offers insights through visualizations such as activity trends, word clouds, and emoji analysis, making it a valuable tool for understanding communication patterns and user statistics in group or individual chats.",
    "tags": [
      "Streamlit",
      "Pandas",
      "Matplotlib",
      "Seaborn",
      "Plotly"
    ],
    "domains": [
      "Data Analysis"
    ],
    "image": "📊",
    "githubUrl": "https://github.com/Akshats-git/Whatsapp-Chat-Analyzer"
  }
];

export const skillCategories: SkillCategory[] = [
  {
    "name": "Frontend",
    "skills": [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Redux"
    ]
  },
  {
    "name": "Backend",
    "skills": [
      "Node.js",
      "Express",
      "Python",
      "FastAPI"
    ]
  },
  {
    "name": "Databases",
    "skills": [
      "PostgreSQL",
      "MongoDB",
      "Firebase",
      "Redis",
      "MySQL"
    ]
  },
  {
    "name": "Tools & Platforms",
    "skills": [
      "Git",
      "Docker",
      "AWS",
      "Vercel",
      "GitHub Actions",
      "VS Code"
    ]
  },
  {
    "name": "UI/UX & Design",
    "skills": [
      "Figma",
      "Shadcn UI",
      "Material-UI"
    ]
  },
  {
    "name": "Agentic Frameworks",
    "skills": [
      "LangChain",
      "Hugging Face",
      "RAG Systems",
      "LangGraph"
    ]
  }
];
